name: Dependabot auto-merge
on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: number

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      (github.event_name == 'workflow_dispatch')
    steps:
      - name: Get PR URL
        id: pr_url
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "PR_URL=https://github.com/${{ github.repository }}/pull/${{ github.event.inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT
          fi

      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ steps.pr_url.outputs.PR_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ steps.pr_url.outputs.PR_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
