name: Dependabot auto-merge
on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get open Dependabot PRs
        id: dependabot_prs
        run: |
          prs=$(gh pr list --author app/dependabot --json number,url --jq '.[].url')
          echo "PR_LIST<<EOF" >> $GITHUB_OUTPUT
          echo "$prs" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process Dependabot PRs
        run: |
          while IFS= read -r PR_URL; do
            echo "Processing PR: $PR_URL"
            
            # Check PR status
            PR_STATUS=$(gh pr view "$PR_URL" --json statusCheckRollup --jq '.statusCheckRollup[].state' | sort -u)
            if [ "$PR_STATUS" = "SUCCESS" ]; then
              echo "All checks passed. Approving and enabling auto-merge."
              
              # Approve PR
              gh pr review --approve "$PR_URL"
              
              # Enable auto-merge
              gh pr merge --auto --merge "$PR_URL"
            else
              echo "Some checks have not passed. Skipping approval and auto-merge."
            fi
            
            echo "---"
          done <<< "${{ steps.dependabot_prs.outputs.PR_LIST }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
