name: Python Application Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask apps
        run: |
          flask --app corsapp run &
          sleep 3
          flask --app longpoll run &
          sleep 3
          flask --app sse run &
          sleep 3
          flask --app sync run &
          sleep 3
          flask --app taskapp run &
          sleep 3
          flask --app webhook run &
          sleep 3
          flask --app websockets run &
          sleep 3
          pkill -f flask
