name: Python Application Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask apps
        run: |
          flask --app corsapp run -p 5001 &
          flask --app longpoll run -p 5002 &
          flask --app sse run -p 5003 &
          flask --app sync run -p 5004 &
          flask --app taskapp run -p 5005 &
          flask --app webhook run -p 5006 &
          flask --app websockets run -p 5007 &
          sleep 3
          pkill -f flask
