name: Scheduled Dependabot Merge
on:
  schedule:
    - cron: "0 1 * * *" # Runs every day at 1am
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get open Dependabot PRs
        id: get-prs
        run: |
          prs=$(gh pr list --repo ${{ github.repository }} --author app/dependabot --json number --jq 'map(.number) | join(" ")' || echo "")
          if [ -z "$prs" ]; then
            echo "No open Dependabot PRs found"
            echo "pr_list=" >> $GITHUB_OUTPUT
          else
            echo "Found open Dependabot PRs: $prs"
            echo "pr_list=$prs" >> $GITHUB_OUTPUT
          fi
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Process PRs
        if: steps.get-prs.outputs.pr_list != ''
        run: |
          for pr in ${{ steps.get-prs.outputs.pr_list }}; do
            echo "Processing PR #$pr"
            
            # Fetch metadata
            metadata=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/pulls/$pr)
            
            # Extract package ecosystem and update type
            pr_body=$(echo "$metadata" | jq -r '.body')
            package_ecosystem=$(echo "$pr_body" | grep -oP '(?<=\*\*Package ecosystem\*\*: )[^\n]+' || echo "unknown")
            dependency=$(echo "$metadata" | jq -r '.title' | grep -oP 'Bump \K.+(?= from)')
            update_type=$(echo "$metadata" | jq -r '.title' | grep -oP 'Bump .+ from .+ to .+')
            
            # Determine the actual package ecosystem
            if [[ "$package_ecosystem" == "@dependabot rebase" ]]; then
              if [[ "$dependency" == *".py" || "$dependency" == "pip" || "$dependency" == "flask"* || "$dependency" == "markupsafe" ]]; then
                package_ecosystem="pip"
              elif [[ "$dependency" == *".js" || "$dependency" == "npm" || "$dependency" == "stripe" ]]; then
                package_ecosystem="npm"
              elif [[ "$dependency" == "actions/"* ]]; then
                package_ecosystem="github-actions"
              else
                package_ecosystem="unknown"
              fi
            fi
            
            # Show package ecosystem and update type
            echo "Package Ecosystem: $package_ecosystem"
            echo "Dependency: $dependency"
            echo "Update Type: $update_type"
            
            if [[ "$package_ecosystem" == "npm" || "$package_ecosystem" == "github-actions" || "$package_ecosystem" == "pip" ]]; then
              if [[ ! "$update_type" =~ .*"major".* ]]; then
                echo "Approving and auto-merging PR #$pr"
                gh pr review $pr --approve
                gh pr merge $pr --auto --squash
              else
                echo "Skipping major update PR #$pr"
              fi
            else
              echo "Skipping PR #$pr (not npm, GitHub Actions, or pip)"
            fi
          done
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
