name: Scheduled Dependabot Merge
on:
  schedule:
    - cron: "0 1 * * *" # Runs every day at 1am
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get open Dependabot PRs
        id: get-prs
        run: |
          prs=$(gh pr list --repo ${{ github.repository }} --author app/dependabot --json number --jq 'map(.number) | join(" ")' || echo "")
          if [ -z "$prs" ]; then
            echo "No open Dependabot PRs found"
            echo "pr_list=" >> $GITHUB_OUTPUT
          else
            echo "Found open Dependabot PRs: $prs"
            echo "pr_list=$prs" >> $GITHUB_OUTPUT
          fi
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Process PRs
        if: steps.get-prs.outputs.pr_list != ''
        run: |
          for pr in ${{ steps.get-prs.outputs.pr_list }}; do
            echo "Processing PR #$pr"
            echo "Approving and auto-merging PR #$pr"
            gh pr review $pr --approve
            gh pr merge $pr --auto --squash
          done
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
